name: Windows CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        cinst wget
        cinst meson
        c:\ProgramData\chocolatey\bin\wget.exe http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28-w64-setup.exe
        .\libsndfile-1.0.28-w64-setup.exe /silent /sp- /norestart
    - name: configure
      run: |
        meson build
    - name: make
      run: |
        ninja -C build

