name: Windows .NET CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        msbuild dotnet\rubberband.sln

